import {questions} from './data.js';
import {createGame,answer,next,hint,score} from './core.js';
import {CAMPAIGN_URL,REGISTRATION_URL} from './config.js';
import {headerState} from './header.js';
document.querySelector('#brand').href=CAMPAIGN_URL;
document.querySelector('#registration').href=REGISTRATION_URL;
const main=document.querySelector('main');
const gameStatus=document.querySelector('#game-status');
let game, busy=false;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sources=q=>`<nav class="sources" aria-label="Источники">${q.sources.map(s=>`<a href="${escape(s.url)}" target="_blank" rel="noopener noreferrer">${escape(s.label)} ↗</a>`).join('')}</nav>`;
function focusHeading(){main.querySelector('h1,h2')?.focus({preventScroll:true}); window.scrollTo({top:0,behavior:'instant'});}
function renderHeader(screen){
 const state=headerState({screen,index:game?.index??0,answers:game?.answers??[],total:questions.length});
 gameStatus.hidden=!state.visible;
 if(!state.visible){gameStatus.innerHTML='';return;}
 const labels=state.segments.map((segment,i)=>`Вопрос ${i+1}: ${segment==='correct'?'верно':segment==='incorrect'?'неверно':segment==='current'?'текущий':'впереди'}`);
 const bar=state.showProgress?`<div class="progress" role="progressbar" aria-label="Пройдено вопросов" aria-valuemin="0" aria-valuemax="${questions.length}" aria-valuenow="${game.answers.length}" aria-valuetext="${labels.join('. ')}">${state.segments.map((segment,i)=>`<span class="${segment}" title="${labels[i]}" aria-hidden="true"></span>`).join('')}</div>`:'';
 gameStatus.innerHTML=`<div class="game-status-row"><strong>${state.title}</strong><span>${state.counter}</span></div>${bar}`;
}
function intro(){renderHeader('intro');main.innerHTML=`<section class="intro"><div class="eyebrow">история умеет удивлять</div><h1 tabindex="-1">При ком<span class="coral">?</span></h1><p class="lead">Событие помнишь.<br>А кто тогда был премьером?</p><div class="intro-scene"><div class="teaser"><span>например</span><p>Эйнштейну предложили<br>стать президентом Израиля.</p><span class="teaser-bottom">вот это поворот <span aria-hidden="true">↻</span></span></div><img src="./assets/character.png" alt="" class="character"></div><div class="intro-bottom"><p class="meta">8 событий <span>·</span> 4 имени на выбор</p><button class="primary" id="start">играть <span aria-hidden="true">→</span></button></div></section>`; main.querySelector('#start').onclick=()=>{const previous=game?.deck.map(q=>q.id).join(); game=createGame(questions); if(game.deck.map(q=>q.id).join()===previous)game.deck.push(game.deck.shift()); renderQuestion();};}
function renderQuestion(){busy=false;renderHeader('play');const q=game.deck[game.index];main.innerHTML=`<section class="play"><article class="question-card"><div class="eyebrow">${escape(q.category)}</div><h1 tabindex="-1">${escape(q.question)}</h1><p class="small question-label">кто тогда был премьер-министром?</p><div class="options">${q.options.map((o,i)=>`<button class="option" data-answer="${escape(o)}" ${game.hidden.includes(o)?'disabled':''}><span class="option-number" aria-hidden="true">${i+1}</span><span>${escape(o)}</span><span class="option-arrow" aria-hidden="true">↗</span></button>`).join('')}</div></article><div class="below-card"><button id="hint" class="text-button" ${game.hintUsed?'disabled':''}>${game.hintUsed?'подсказка использована':'убрать два варианта'}</button><span class="small">один раз за игру</span></div><p class="hint-status" role="status">${game.hidden.length?'Два неверных варианта убраны. Выбирай из оставшихся.':''}</p></section>`;
main.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(busy)return;busy=true;answer(game,b.dataset.answer);main.querySelectorAll('button').forEach(x=>x.disabled=true);const card=main.querySelector('article');card.classList.add('turn-out');const delay=matchMedia('(prefers-reduced-motion: reduce)').matches?0:180;setTimeout(renderStory,delay);});
main.querySelector('#hint').onclick=()=>{hint(game);renderQuestion();main.querySelector('.option:not(:disabled)')?.focus({preventScroll:true});};focusHeading();}
function renderStory(){renderHeader('play');const q=game.deck[game.index],a=game.answers[game.index];main.innerHTML=`<section class="play"><article class="story-card turn-in"><div class="answer-status" role="status">${a.correct?'Верно!':'Это было при другом премьере.'}${a.hint?' <span>С подсказкой</span>':''}</div><div class="answer-heading"><span class="year">${q.year}</span><div><h1 tabindex="-1">${escape(q.correct)}</h1>${q.dateNote?`<span class="small">${escape(q.dateNote)}</span>`:''}</div></div>${!a.correct?`<p class="your-answer">Твой ответ: ${escape(a.value)}</p>`:''}<div class="story"><div class="eyebrow">обратная сторона истории</div><h2>${escape(q.title)}</h2><p>${escape(q.story[0])}</p><details><summary>читать историю целиком <span aria-hidden="true">↓</span></summary>${q.story.slice(1).map(p=>`<p>${escape(p)}</p>`).join('')}${sources(q)}</details></div></article><button class="primary next" id="next">${game.index===7?'посмотреть результат':'следующее событие'} <span aria-hidden="true">→</span></button></section>`;main.querySelector('#next').onclick=()=>{next(game);game.done?renderResult():renderQuestion();};focusHeading();}
function renderResult(){renderHeader('result');main.innerHTML=`<section class="result"><div class="eyebrow">вот и вся история. пока!</div><h1 tabindex="-1">${score(game)} <span class="muted">из 8</span></h1><p class="lead">${score(game)===8?'Все события на своих местах.':'Теперь у этих событий есть имена.'}</p><div class="result-note"><img class="result-character" src="./assets/character.png" alt=""><p>Восемь историй,<br>которые можно<br>рассказать дальше.</p></div><p class="small">${game.hintUsed?'Один ответ — с подсказкой.':'Ты прошёл игру без подсказки.'}</p><button id="again" class="primary">сыграть ещё раз <span aria-hidden="true">↻</span></button><p class="small replay-note">Те же истории, новый порядок вопросов.</p><div class="timeline-header"><h2>Теперь по порядку</h2><p class="small">Открой событие, чтобы перечитать историю.</p></div><div class="timeline">${[...game.deck].sort((a,b)=>a.year-b.year).map(q=>{const a=game.answers.find(a=>a.id===q.id);return `<details class="timeline-item"><summary><span class="timeline-year">${q.year}</span><span><strong>${escape(q.title)}</strong><span class="timeline-name">${escape(q.correct)} <span aria-label="${a.correct?'ответ верный':'ответ неверный'}">${a.correct?'✓':'○'}</span></span></span><span aria-hidden="true">+</span></summary><div class="timeline-story">${q.story.map(p=>`<p>${escape(p)}</p>`).join('')}${sources(q)}</div></details>`;}).join('')}</div><p class="small premise">«При ком» означает, кто возглавлял правительство в тот момент. Это не оценка заслуг или ответственности премьера.</p><a class="registration result-register" href="${REGISTRATION_URL}" target="_blank" rel="noopener noreferrer">Идёшь голосовать? <strong>Регистрируйся! ↗</strong></a></section>`;main.querySelector('#again').onclick=()=>{intro();main.querySelector('#start').click();};focusHeading();}
document.querySelector('#privacy').onclick=()=>document.querySelector('#privacy-dialog').showModal();
intro();
